pub const eadk_color_t = u16;
pub const eadk_color_black: eadk_color_t = 0x0000;
pub const eadk_color_white: eadk_color_t = 0xFFFF;
pub const eadk_color_red: eadk_color_t = 0xF800;
pub const eadk_color_green: eadk_color_t = 0x07E0;
pub const eadk_color_blue: eadk_color_t = 0x001F;
pub const eadk_point_t = extern struct {
    x: u16 = 0,
    y: u16 = 0,
};
pub const eadk_rect_t = extern struct {
    x: u16 = 0,
    y: u16 = 0,
    width: u16 = 0,
    height: u16 = 0,
};
pub const eadk_screen_rect: eadk_rect_t = eadk_rect_t{
    .x = 0,
    .y = 0,
    .width = 320,
    .height = 240,
};
pub const eadk_keyboard_state_t = u64;
pub const eadk_key_left: c_int = 0;
pub const eadk_key_up: c_int = 1;
pub const eadk_key_down: c_int = 2;
pub const eadk_key_right: c_int = 3;
pub const eadk_key_ok: c_int = 4;
pub const eadk_key_back: c_int = 5;
pub const eadk_key_home: c_int = 6;
pub const eadk_key_on_off: c_int = 8;
pub const eadk_key_shift: c_int = 12;
pub const eadk_key_alpha: c_int = 13;
pub const eadk_key_xnt: c_int = 14;
pub const eadk_key_var: c_int = 15;
pub const eadk_key_toolbox: c_int = 16;
pub const eadk_key_backspace: c_int = 17;
pub const eadk_key_exp: c_int = 18;
pub const eadk_key_ln: c_int = 19;
pub const eadk_key_log: c_int = 20;
pub const eadk_key_imaginary: c_int = 21;
pub const eadk_key_comma: c_int = 22;
pub const eadk_key_power: c_int = 23;
pub const eadk_key_sine: c_int = 24;
pub const eadk_key_cosine: c_int = 25;
pub const eadk_key_tangent: c_int = 26;
pub const eadk_key_pi: c_int = 27;
pub const eadk_key_sqrt: c_int = 28;
pub const eadk_key_square: c_int = 29;
pub const eadk_key_seven: c_int = 30;
pub const eadk_key_eight: c_int = 31;
pub const eadk_key_nine: c_int = 32;
pub const eadk_key_left_parenthesis: c_int = 33;
pub const eadk_key_right_parenthesis: c_int = 34;
pub const eadk_key_four: c_int = 36;
pub const eadk_key_five: c_int = 37;
pub const eadk_key_six: c_int = 38;
pub const eadk_key_multiplication: c_int = 39;
pub const eadk_key_division: c_int = 40;
pub const eadk_key_one: c_int = 42;
pub const eadk_key_two: c_int = 43;
pub const eadk_key_three: c_int = 44;
pub const eadk_key_plus: c_int = 45;
pub const eadk_key_minus: c_int = 46;
pub const eadk_key_zero: c_int = 48;
pub const eadk_key_dot: c_int = 49;
pub const eadk_key_ee: c_int = 50;
pub const eadk_key_ans: c_int = 51;
pub const eadk_key_exe: c_int = 52;
pub const eadk_key_t = c_uint;
pub extern fn eadk_keyboard_scan(...) eadk_keyboard_state_t;
pub fn eadk_keyboard_key_down(state: eadk_keyboard_state_t, key: eadk_key_t) bool {
    return ((state >> @truncate(key)) & 1) > 0;
}
pub const eadk_event_t = u16;
pub const eadk_event_left: c_int = 0;
pub const eadk_event_up: c_int = 1;
pub const eadk_event_down: c_int = 2;
pub const eadk_event_right: c_int = 3;
pub const eadk_event_ok: c_int = 4;
pub const eadk_event_back: c_int = 5;
pub const eadk_event_shift: c_int = 12;
pub const eadk_event_alpha: c_int = 13;
pub const eadk_event_xnt: c_int = 14;
pub const eadk_event_var: c_int = 15;
pub const eadk_event_toolbox: c_int = 16;
pub const eadk_event_backspace: c_int = 17;
pub const eadk_event_exp: c_int = 18;
pub const eadk_event_ln: c_int = 19;
pub const eadk_event_log: c_int = 20;
pub const eadk_event_imaginary: c_int = 21;
pub const eadk_event_comma: c_int = 22;
pub const eadk_event_power: c_int = 23;
pub const eadk_event_sine: c_int = 24;
pub const eadk_event_cosine: c_int = 25;
pub const eadk_event_tangent: c_int = 26;
pub const eadk_event_pi: c_int = 27;
pub const eadk_event_sqrt: c_int = 28;
pub const eadk_event_square: c_int = 29;
pub const eadk_event_seven: c_int = 30;
pub const eadk_event_eight: c_int = 31;
pub const eadk_event_nine: c_int = 32;
pub const eadk_event_left_parenthesis: c_int = 33;
pub const eadk_event_right_parenthesis: c_int = 34;
pub const eadk_event_four: c_int = 36;
pub const eadk_event_five: c_int = 37;
pub const eadk_event_six: c_int = 38;
pub const eadk_event_multiplication: c_int = 39;
pub const eadk_event_division: c_int = 40;
pub const eadk_event_one: c_int = 42;
pub const eadk_event_two: c_int = 43;
pub const eadk_event_three: c_int = 44;
pub const eadk_event_plus: c_int = 45;
pub const eadk_event_minus: c_int = 46;
pub const eadk_event_zero: c_int = 48;
pub const eadk_event_dot: c_int = 49;
pub const eadk_event_ee: c_int = 50;
pub const eadk_event_ans: c_int = 51;
pub const eadk_event_exe: c_int = 52;
pub const eadk_event_shift_left: c_int = 54;
pub const eadk_event_shift_up: c_int = 55;
pub const eadk_event_shift_down: c_int = 56;
pub const eadk_event_shift_right: c_int = 57;
pub const eadk_event_alpha_lock: c_int = 67;
pub const eadk_event_cut: c_int = 68;
pub const eadk_event_copy: c_int = 69;
pub const eadk_event_paste: c_int = 70;
pub const eadk_event_clear: c_int = 71;
pub const eadk_event_left_bracket: c_int = 72;
pub const eadk_event_right_bracket: c_int = 73;
pub const eadk_event_left_brace: c_int = 74;
pub const eadk_event_right_brace: c_int = 75;
pub const eadk_event_underscore: c_int = 76;
pub const eadk_event_sto: c_int = 77;
pub const eadk_event_arcsine: c_int = 78;
pub const eadk_event_arccosine: c_int = 79;
pub const eadk_event_arctangent: c_int = 80;
pub const eadk_event_equal: c_int = 81;
pub const eadk_event_lower: c_int = 82;
pub const eadk_event_greater: c_int = 83;
pub const eadk_event_colon: c_int = 122;
pub const eadk_event_semicolon: c_int = 123;
pub const eadk_event_double_quotes: c_int = 124;
pub const eadk_event_percent: c_int = 125;
pub const eadk_event_lower_a: c_int = 126;
pub const eadk_event_lower_b: c_int = 127;
pub const eadk_event_lower_c: c_int = 128;
pub const eadk_event_lower_d: c_int = 129;
pub const eadk_event_lower_e: c_int = 130;
pub const eadk_event_lower_f: c_int = 131;
pub const eadk_event_lower_g: c_int = 132;
pub const eadk_event_lower_h: c_int = 133;
pub const eadk_event_lower_i: c_int = 134;
pub const eadk_event_lower_j: c_int = 135;
pub const eadk_event_lower_k: c_int = 136;
pub const eadk_event_lower_l: c_int = 137;
pub const eadk_event_lower_m: c_int = 138;
pub const eadk_event_lower_n: c_int = 139;
pub const eadk_event_lower_o: c_int = 140;
pub const eadk_event_lower_p: c_int = 141;
pub const eadk_event_lower_q: c_int = 142;
pub const eadk_event_lower_r: c_int = 144;
pub const eadk_event_lower_s: c_int = 145;
pub const eadk_event_lower_t: c_int = 146;
pub const eadk_event_lower_u: c_int = 147;
pub const eadk_event_lower_v: c_int = 148;
pub const eadk_event_lower_w: c_int = 150;
pub const eadk_event_lower_x: c_int = 151;
pub const eadk_event_lower_y: c_int = 152;
pub const eadk_event_lower_z: c_int = 153;
pub const eadk_event_space: c_int = 154;
pub const eadk_event_question: c_int = 156;
pub const eadk_event_exclamation: c_int = 157;
pub const eadk_event_upper_a: c_int = 180;
pub const eadk_event_upper_b: c_int = 181;
pub const eadk_event_upper_c: c_int = 182;
pub const eadk_event_upper_d: c_int = 183;
pub const eadk_event_upper_e: c_int = 184;
pub const eadk_event_upper_f: c_int = 185;
pub const eadk_event_upper_g: c_int = 186;
pub const eadk_event_upper_h: c_int = 187;
pub const eadk_event_upper_i: c_int = 188;
pub const eadk_event_upper_j: c_int = 189;
pub const eadk_event_upper_k: c_int = 190;
pub const eadk_event_upper_l: c_int = 191;
pub const eadk_event_upper_m: c_int = 192;
pub const eadk_event_upper_n: c_int = 193;
pub const eadk_event_upper_o: c_int = 194;
pub const eadk_event_upper_p: c_int = 195;
pub const eadk_event_upper_q: c_int = 196;
pub const eadk_event_upper_r: c_int = 198;
pub const eadk_event_upper_s: c_int = 199;
pub const eadk_event_upper_t: c_int = 200;
pub const eadk_event_upper_u: c_int = 201;
pub const eadk_event_upper_v: c_int = 202;
pub const eadk_event_upper_w: c_int = 204;
pub const eadk_event_upper_x: c_int = 205;
pub const eadk_event_upper_y: c_int = 206;
pub const eadk_event_upper_z: c_int = 207;
pub extern fn eadk_event_get(timeout: [*c]i32) eadk_event_t;
pub extern fn eadk_backlight_set_brightness(brightness: u8) void;
pub extern fn eadk_backlight_brightness(...) u8;
pub extern fn eadk_battery_is_charging(...) bool;
pub extern fn eadk_battery_level(...) u8;
pub extern fn eadk_battery_voltage(...) f32;
pub extern fn eadk_display_push_rect(rect: eadk_rect_t, pixels: [*c]const eadk_color_t) void;
pub extern fn eadk_display_push_rect_uniform(rect: eadk_rect_t, color: eadk_color_t) void;
pub extern fn eadk_display_pull_rect(rect: eadk_rect_t, pixels: [*c]eadk_color_t) void;
pub extern fn eadk_display_wait_for_vblank(...) bool;
pub extern fn eadk_display_draw_string(text: [*c]const u8, point: eadk_point_t, large_font: bool, text_color: eadk_color_t, background_color: eadk_color_t) void;
pub extern fn eadk_timing_usleep(us: u32) void;
pub extern fn eadk_timing_msleep(ms: u32) void;
pub extern fn eadk_timing_millis(...) u64;
pub extern var eadk_external_data: [*c]const u8;
pub extern var eadk_external_data_size: usize;
pub extern fn eadk_usb_is_plugged(...) bool;
pub extern fn eadk_random(...) u32;
pub const EADK_SCREEN_WIDTH = @as(c_int, 320);
pub const EADK_SCREEN_HEIGHT = @as(c_int, 240);
